package com.google.android.material;

public final class ComGoogleAndroidMaterialR$anim {
    public static final int abc_fade_in = pcc.abc_fade_in;
    public static final int abc_fade_out = pcc.abc_fade_out;
    public static final int abc_grow_fade_in_from_bottom = pcc.abc_grow_fade_in_from_bottom;
    public static final int abc_popup_enter = pcc.abc_popup_enter;
    public static final int abc_popup_exit = pcc.abc_popup_exit;
    public static final int abc_shrink_fade_out_from_bottom = pcc.abc_shrink_fade_out_from_bottom;
    public static final int abc_slide_in_bottom = pcc.abc_slide_in_bottom;
    public static final int abc_slide_in_top = pcc.abc_slide_in_top;
    public static final int abc_slide_out_bottom = pcc.abc_slide_out_bottom;
    public static final int abc_slide_out_top = pcc.abc_slide_out_top;
    public static final int abc_tooltip_enter = pcc.abc_tooltip_enter;
    public static final int abc_tooltip_exit = pcc.abc_tooltip_exit;
    public static final int btn_checkbox_to_checked_box_inner_merged_animation = pcc.btn_checkbox_to_checked_box_inner_merged_animation;
    public static final int btn_checkbox_to_checked_box_outer_merged_animation = pcc.btn_checkbox_to_checked_box_outer_merged_animation;
    public static final int btn_checkbox_to_checked_icon_null_animation = pcc.btn_checkbox_to_checked_icon_null_animation;
    public static final int btn_checkbox_to_unchecked_box_inner_merged_animation = pcc.btn_checkbox_to_unchecked_box_inner_merged_animation;
    public static final int btn_checkbox_to_unchecked_check_path_merged_animation = pcc.btn_checkbox_to_unchecked_check_path_merged_animation;
    public static final int btn_checkbox_to_unchecked_icon_null_animation = pcc.btn_checkbox_to_unchecked_icon_null_animation;
    public static final int btn_radio_to_off_mtrl_dot_group_animation = pcc.btn_radio_to_off_mtrl_dot_group_animation;
    public static final int btn_radio_to_off_mtrl_ring_outer_animation = pcc.btn_radio_to_off_mtrl_ring_outer_animation;
    public static final int btn_radio_to_off_mtrl_ring_outer_path_animation = pcc.btn_radio_to_off_mtrl_ring_outer_path_animation;
    public static final int btn_radio_to_on_mtrl_dot_group_animation = pcc.btn_radio_to_on_mtrl_dot_group_animation;
    public static final int btn_radio_to_on_mtrl_ring_outer_animation = pcc.btn_radio_to_on_mtrl_ring_outer_animation;
    public static final int btn_radio_to_on_mtrl_ring_outer_path_animation = pcc.btn_radio_to_on_mtrl_ring_outer_path_animation;
    public static final int design_bottom_sheet_slide_in = pcc.design_bottom_sheet_slide_in;
    public static final int design_bottom_sheet_slide_out = pcc.design_bottom_sheet_slide_out;
    public static final int design_snackbar_in = pcc.design_snackbar_in;
    public static final int design_snackbar_out = pcc.design_snackbar_out;
    public static final int fragment_fast_out_extra_slow_in = pcc.fragment_fast_out_extra_slow_in;
    public static final int linear_indeterminate_line1_head_interpolator = pcc.linear_indeterminate_line1_head_interpolator;
    public static final int linear_indeterminate_line1_tail_interpolator = pcc.linear_indeterminate_line1_tail_interpolator;
    public static final int linear_indeterminate_line2_head_interpolator = pcc.linear_indeterminate_line2_head_interpolator;
    public static final int linear_indeterminate_line2_tail_interpolator = pcc.linear_indeterminate_line2_tail_interpolator;
    public static final int m3_bottom_sheet_slide_in = pcc.m3_bottom_sheet_slide_in;
    public static final int m3_bottom_sheet_slide_out = pcc.m3_bottom_sheet_slide_out;
    public static final int m3_motion_fade_enter = pcc.m3_motion_fade_enter;
    public static final int m3_motion_fade_exit = pcc.m3_motion_fade_exit;
    public static final int m3_side_sheet_enter_from_left = pcc.m3_side_sheet_enter_from_left;
    public static final int m3_side_sheet_enter_from_right = pcc.m3_side_sheet_enter_from_right;
    public static final int m3_side_sheet_exit_to_left = pcc.m3_side_sheet_exit_to_left;
    public static final int m3_side_sheet_exit_to_right = pcc.m3_side_sheet_exit_to_right;
    public static final int mtrl_bottom_sheet_slide_in = pcc.mtrl_bottom_sheet_slide_in;
    public static final int mtrl_bottom_sheet_slide_out = pcc.mtrl_bottom_sheet_slide_out;
    public static final int mtrl_card_lowers_interpolator = pcc.mtrl_card_lowers_interpolator;
}
