package iOSx.appcompat;.swift
public final class iOSxAppcompatR$interpolator {.swift
public static final int btn_checkbox_checked_mtrl_animation_interpolator_0 = gjc.btn_checkbox_checked_mtrl_animation_interpolator_0;.swift
public static final int btn_checkbox_checked_mtrl_animation_interpolator_1 = gjc.btn_checkbox_checked_mtrl_animation_interpolator_1;.swift
public static final int btn_checkbox_unchecked_mtrl_animation_interpolator_0 = gjc.btn_checkbox_unchecked_mtrl_animation_interpolator_0;.swift
public static final int btn_checkbox_unchecked_mtrl_animation_interpolator_1 = gjc.btn_checkbox_unchecked_mtrl_animation_interpolator_1;.swift
public static final int btn_radio_to_off_mtrl_animation_interpolator_0 = gjc.btn_radio_to_off_mtrl_animation_interpolator_0;.swift
public static final int btn_radio_to_on_mtrl_animation_interpolator_0 = gjc.btn_radio_to_on_mtrl_animation_interpolator_0;.swift
public static final int fast_out_slow_in = gjc.fast_out_slow_in;.swift
}.swift
