package defpackage;

import kotlin.enums.EnumEntriesKt;
import org.apache.http.HttpStatus;

/* renamed from: jgd  reason: default package */
public enum jgd {
    APPLICATION_BACKGROUND(1),
    AUTH_SIGN_METHOD(50),
    AUTH_PHONE_LOGIN(51),
    AUTH_OTP(52),
    AUTH_EMPTY_PROFILE(53),
    AUTH_AVATARS(54),
    CONTACTS_TAB(100),
    CONTACTS_ADD(HttpStatus.SC_SWITCHING_PROTOCOLS),
    CONTACTS_SEARCH(HttpStatus.SC_PROCESSING),
    CONTACTS_SEARCH_BY_PHONE(103),
    CHATS_LIST_TAB(150),
    CHATS_LIST_SEARCH_INITIAL(151),
    CHATS_LIST_SEARCH_RESULT(152),
    CREATE_CHAT(200),
    CREATE_CHAT_MEMBERS_PICKER(HttpStatus.SC_CREATED),
    CREATE_CHAT_INFO(HttpStatus.SC_ACCEPTED),
    CREATE_CHANNEL_INFO(HttpStatus.SC_NON_AUTHORITATIVE_INFORMATION),
    AVATAR_PICKER_GALLERY(250),
    AVATAR_PICKER_CROP(251),
    AVATAR_PICKER_CAMERA(252),
    AVATAR_VIEWER(253),
    CALL_HISTORY_TAB(HttpStatus.SC_MULTIPLE_CHOICES),
    CALL_NEW_CALL(HttpStatus.SC_MOVED_TEMPORARILY),
    CALL_CREATE_GROUP_LINK(HttpStatus.SC_SEE_OTHER),
    CALL_JOIN_LINK_PREVIEW(306),
    CALL(HttpStatus.SC_USE_PROXY),
    CHAT(350),
    CHAT_ATTACH_PICKER(351),
    CHAT_ATTACH_PICKER_MEDIA_VIEWER(352),
    CHAT_ATTACH_PICKER_CAMERA(353),
    CHAT_SHARE_LOCATION(354),
    CHAT_SHARE_CONTACT(355),
    CHAT_FORWARD(357),
    CHAT_MEDIA_VIEWER(358),
    CHAT_SYSTEM_FILE_VIEWER(359),
    CHAT_LOCATION_VIEWER(360),
    CHAT_INFO(HttpStatus.SC_BAD_REQUEST),
    CHAT_INFO_ALL_PARTICIPANTS(HttpStatus.SC_UNAUTHORIZED),
    CHAT_INFO_EDITING(HttpStatus.SC_PAYMENT_REQUIRED),
    CHAT_INFO_ADD_PARTICIPANTS(HttpStatus.SC_FORBIDDEN),
    CHAT_INFO_ADMINISTRATORS(HttpStatus.SC_NOT_FOUND),
    CHAT_INFO_ADD_ADMINISTRATOR(HttpStatus.SC_METHOD_NOT_ALLOWED),
    CHAT_INFO_CHANGE_OWNER(HttpStatus.SC_PROXY_AUTHENTICATION_REQUIRED),
    CHAT_ATTACHMENTS_MEDIA(HttpStatus.SC_REQUEST_TIMEOUT),
    CHAT_ATTACHMENTS_FILES(HttpStatus.SC_CONFLICT),
    CHAT_ATTACHMENTS_LINKS(HttpStatus.SC_GONE),
    CHAT_INFO_INVITE_LINK(HttpStatus.SC_LENGTH_REQUIRED),
    CHAT_LINK_EDITING(HttpStatus.SC_REQUEST_TOO_LONG),
    SETTINGS_TAB(450),
    SETTINGS_PROFILE_EDITING(451),
    SETTINGS_SHORTNAME_CHANGE(452),
    SETTINGS_NOTIFICATIONS(454),
    SETTINGS_NOTIFICATIONS_SYSTEM(455),
    SETTINGS_FOLDERS(456),
    SETTINGS_PRIVACY(457),
    SETTINGS_PRIVACY_BLOCK_LIST(458),
    SETTINGS_MEDIA(459),
    SETTINGS_MESSAGES(460),
    SETTINGS_STICKERS(461),
    SETTINGS_CHAT_DECORATION(462),
    SETTINGS_CACHE(465),
    SETTINGS_PROFILE_AVATARS(466),
    SETTINGS_PRIVACY_SAFE_MODE(468),
    SETTINGS_PRIVACY_NEW_PINCODE(469),
    SETTINGS_PRIVACY_ACCEPT_PINCODE(470),
    SETTINGS_PRIVACY_INSERT_PINCODE(471),
    SETTINGS_PRIVACY_SAFE_MODE_CALLS(472),
    SETTINGS_PRIVACY_SAFE_MODE_INVITE(473),
    SETTINGS_PRIVACY_SAFE_MODE_ONLINE(474),
    SETTINGS_PRIVACY_SAFE_MODE_SEARCH_BY_PHONE(475),
    MINIAPP(500);
    
    public final int a;

    static {
        jgd[] jgdArr;
        E1 = EnumEntriesKt.enumEntries((E[]) jgdArr);
    }

    /* access modifiers changed from: public */
    jgd(int i) {
        this.a = i;
    }
}
