package defpackage;

import android.graphics.drawable.Drawable;
import android.text.TextUtils;
import android.util.AttributeSet;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.appcompat.widget.AppCompatTextView;
import androidx.appcompat.widget.Toolbar;
import androidx.coordinatorlayout.widget.CoordinatorLayout;
import androidx.core.widget.NestedScrollView;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.b;
import com.google.android.material.appbar.AppBarLayout;
import kotlin.Unit;
import kotlin.coroutines.Continuation;
import kotlin.io.ConstantsKt;
import kotlin.jvm.functions.Function1;
import kotlin.math.MathKt;
import kotlin.reflect.KProperty;
import kotlin.uuid.Uuid;
import one.me.profile.ProfileScreen;
import one.me.sdk.lists.widgets.EndlessRecyclerView2;
import one.me.sdk.uikit.common.avatar.OneMeAvatarView;

/* renamed from: m5c  reason: default package */
public final /* synthetic */ class m5c implements Function1 {
    public final /* synthetic */ int a;
    public final /* synthetic */ ProfileScreen b;

    public /* synthetic */ m5c(ProfileScreen profileScreen, int i) {
        this.a = i;
        this.b = profileScreen;
    }

    public final Object invoke(Object obj) {
        js9 js9 = fu4.k;
        ProfileScreen profileScreen = this.b;
        switch (this.a) {
            case 0:
                AppBarLayout appBarLayout = (AppBarLayout) obj;
                KProperty[] kPropertyArr = ProfileScreen.D0;
                m5c m5c = new m5c(profileScreen, 1);
                profileScreen.getClass();
                i53 i53 = new i53(appBarLayout.getContext(), (AttributeSet) null);
                dn dnVar = new dn(-1, -2);
                dnVar.a = 19;
                i53.setLayoutParams(dnVar);
                i53.setTitleEnabled(false);
                m5c.invoke(i53);
                appBarLayout.addView(i53);
                return Unit.INSTANCE;
            case 1:
                i53 i532 = (i53) obj;
                KProperty[] kPropertyArr2 = ProfileScreen.D0;
                m5c m5c2 = new m5c(profileScreen, 3);
                profileScreen.getClass();
                Toolbar toolbar = new Toolbar(i532.getContext(), (AttributeSet) null);
                f53 f53 = new f53(-1, -2);
                f53.a = 1;
                toolbar.setLayoutParams(f53);
                toolbar.setNavigationIcon((Drawable) null);
                toolbar.u(0, 0);
                m5c2.invoke(toolbar);
                i532.addView(toolbar);
                m5c m5c3 = new m5c(profileScreen, 4);
                LinearLayout linearLayout = new LinearLayout(i532.getContext());
                linearLayout.setId(jxa.f1);
                f53 f532 = new f53(-1, -2);
                f532.a = 2;
                f532.bottomMargin = MathKt.roundToInt(((float) 16) * vo4.c().getDisplayMetrics().density);
                linearLayout.setLayoutParams(f532);
                linearLayout.setOrientation(1);
                m5c3.invoke(linearLayout);
                i532.addView(linearLayout);
                return Unit.INSTANCE;
            case 2:
                LinearLayout linearLayout2 = (LinearLayout) obj;
                KProperty[] kPropertyArr3 = ProfileScreen.D0;
                profileScreen.getClass();
                EndlessRecyclerView2 endlessRecyclerView2 = new EndlessRecyclerView2(linearLayout2.getContext(), (AttributeSet) null, 6);
                endlessRecyclerView2.setId(jxa.l1);
                endlessRecyclerView2.setLayoutParams(new ViewGroup.LayoutParams(-1, -2));
                endlessRecyclerView2.setItemAnimator((yyc) null);
                endlessRecyclerView2.getContext();
                endlessRecyclerView2.setLayoutManager(new LinearLayoutManager());
                endlessRecyclerView2.setOverScrollMode(2);
                b bVar = new b();
                bVar.setMaxRecycledViews(1, 1);
                bVar.setMaxRecycledViews(2, 1);
                bVar.setMaxRecycledViews(Uuid.SIZE_BITS, 1);
                bVar.setMaxRecycledViews(64, 1);
                bVar.setMaxRecycledViews(32768, 1);
                bVar.setMaxRecycledViews(32, 1);
                bVar.setMaxRecycledViews(16, 1);
                bVar.setMaxRecycledViews(8, 1);
                bVar.setMaxRecycledViews(65536, 1);
                bVar.setMaxRecycledViews(ConstantsKt.DEFAULT_BLOCK_SIZE, 1);
                endlessRecyclerView2.setRecycledViewPool(bVar);
                endlessRecyclerView2.setAdapter(new x5c(((aua) jxb.a.getAccessor().g(aua.class)).a(), profileScreen));
                endlessRecyclerView2.setClipToPadding(false);
                endlessRecyclerView2.setClipChildren(false);
                endlessRecyclerView2.setPager(new k71(9, profileScreen));
                ez9 ez9 = ri7.a;
                ez9 ez92 = new ez9(3);
                ez92.g(1);
                ez92.g(4);
                ez92.g(2);
                endlessRecyclerView2.j(new mnd(js9.e(endlessRecyclerView2.getContext()).f(), new pbb(8, endlessRecyclerView2, ez92), (h9) null, 12));
                float f = (float) 12;
                float f2 = (float) 24;
                bz9 E = y7e.E(MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f), MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f), MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f2), MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f), MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f), MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f), MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f), MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f), MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f), MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f), MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f), ConstantsKt.MINIMUM_BLOCK_SIZE, MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f), 1024, MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f), ConstantsKt.DEFAULT_BLOCK_SIZE, MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f), MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f));
                int roundToInt = MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f);
                int roundToInt2 = MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f);
                int roundToInt3 = MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f2);
                float f3 = (float) 18;
                int roundToInt4 = MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f3);
                int roundToInt5 = MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f3);
                int roundToInt6 = MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f3);
                int roundToInt7 = MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f2);
                int roundToInt8 = MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f3);
                int roundToInt9 = MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f3);
                int roundToInt10 = MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f3);
                int roundToInt11 = MathKt.roundToInt(f3 * vo4.c().getDisplayMetrics().density);
                float f4 = (float) 6;
                float f5 = (float) 10;
                endlessRecyclerView2.j(new ue8(E, y7e.E(roundToInt, roundToInt2, roundToInt3, roundToInt4, roundToInt5, roundToInt6, roundToInt7, roundToInt8, roundToInt9, roundToInt10, roundToInt11, ConstantsKt.MINIMUM_BLOCK_SIZE, 0, 1024, 0, ConstantsKt.DEFAULT_BLOCK_SIZE, MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f4), 0), y7e.E(MathKt.roundToInt(((float) 8) * vo4.c().getDisplayMetrics().density), 0, MathKt.roundToInt(f4 * vo4.c().getDisplayMetrics().density), 0, 0, 0, 0, 0, 0, 0, MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f5), ConstantsKt.DEFAULT_BLOCK_SIZE, MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f5), ConstantsKt.MINIMUM_BLOCK_SIZE, MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f5), 1024, MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f5), MathKt.roundToInt(f5 * vo4.c().getDisplayMetrics().density)), 1));
                Unit unit = Unit.INSTANCE;
                linearLayout2.addView(endlessRecyclerView2);
                FrameLayout frameLayout = new FrameLayout(linearLayout2.getContext());
                frameLayout.setId(jxa.j1);
                LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(-1, -2);
                layoutParams.rightMargin = MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f);
                layoutParams.leftMargin = MathKt.roundToInt(f * vo4.c().getDisplayMetrics().density);
                layoutParams.bottomMargin = MathKt.roundToInt(f2 * vo4.c().getDisplayMetrics().density);
                layoutParams.topMargin = MathKt.roundToInt(((float) 3) * vo4.c().getDisplayMetrics().density);
                frameLayout.setLayoutParams(layoutParams);
                frameLayout.setOutlineProvider(new n04(vo4.c().getDisplayMetrics().density * 16.0f));
                b0h.H(frameLayout, new ln2(3, (Continuation) null, 1));
                linearLayout2.addView(frameLayout);
                return Unit.INSTANCE;
            case 3:
                Toolbar toolbar2 = (Toolbar) obj;
                KProperty[] kPropertyArr4 = ProfileScreen.D0;
                profileScreen.getClass();
                h3b d = o54.d(toolbar2.getContext(), (AttributeSet) null);
                d.setId(jxa.k1);
                d.setForm(z2b.a);
                d.setTextShimmerEnabled(false);
                d.setLeftActions(new p2b(new oo9(25)));
                float f6 = (float) 6;
                d.setPaddingRelative(MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f6), d.getPaddingTop(), MathKt.roundToInt(f6 * vo4.c().getDisplayMetrics().density), d.getPaddingBottom());
                toolbar2.addView(d);
                return Unit.INSTANCE;
            case 4:
                LinearLayout linearLayout3 = (LinearLayout) obj;
                KProperty[] kPropertyArr5 = ProfileScreen.D0;
                profileScreen.getClass();
                OneMeAvatarView oneMeAvatarView = new OneMeAvatarView(linearLayout3.getContext(), (AttributeSet) null);
                oneMeAvatarView.setId(jxa.e1);
                float f7 = (float) 96;
                LinearLayout.LayoutParams layoutParams2 = new LinearLayout.LayoutParams(MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f7), MathKt.roundToInt(f7 * vo4.c().getDisplayMetrics().density));
                layoutParams2.gravity = 1;
                layoutParams2.topMargin = MathKt.roundToInt(((float) 8) * vo4.c().getDisplayMetrics().density);
                oneMeAvatarView.setLayoutParams(layoutParams2);
                linearLayout3.addView(oneMeAvatarView);
                TextView textView = new TextView(linearLayout3.getContext());
                textView.setId(jxa.i1);
                LinearLayout.LayoutParams layoutParams3 = new LinearLayout.LayoutParams(-2, -2);
                float f8 = (float) 20;
                layoutParams3.leftMargin = MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f8);
                layoutParams3.rightMargin = MathKt.roundToInt(f8 * vo4.c().getDisplayMetrics().density);
                layoutParams3.topMargin = MathKt.roundToInt(((float) 16) * vo4.c().getDisplayMetrics().density);
                layoutParams3.gravity = 1;
                textView.setLayoutParams(layoutParams3);
                textView.setMaxLines(3);
                textView.setGravity(1);
                puf.x.b(textView, uy4.b);
                textView.setTextColor(js9.e(textView.getContext()).f().getText().e);
                linearLayout3.addView(textView);
                m5c m5c4 = new m5c(profileScreen, 5);
                LinearLayout linearLayout4 = new LinearLayout(linearLayout3.getContext());
                linearLayout4.setLayoutParams(new ViewGroup.LayoutParams(-1, -2));
                float f9 = (float) 12;
                linearLayout4.setPaddingRelative(MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f9), MathKt.roundToInt(((float) 4) * vo4.c().getDisplayMetrics().density), MathKt.roundToInt(f9 * vo4.c().getDisplayMetrics().density), linearLayout4.getPaddingBottom());
                linearLayout4.setOrientation(0);
                linearLayout4.setBackground((Drawable) null);
                linearLayout4.setGravity(1);
                m5c4.invoke(linearLayout4);
                linearLayout3.addView(linearLayout4);
                return Unit.INSTANCE;
            case 5:
                LinearLayout linearLayout5 = (LinearLayout) obj;
                KProperty[] kPropertyArr6 = ProfileScreen.D0;
                profileScreen.getClass();
                AppCompatTextView appCompatTextView = new AppCompatTextView(linearLayout5.getContext(), (AttributeSet) null);
                appCompatTextView.setId(jxa.U);
                LinearLayout.LayoutParams layoutParams4 = new LinearLayout.LayoutParams(-2, -2);
                float f10 = (float) 20;
                layoutParams4.leftMargin = MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f10);
                appCompatTextView.setLayoutParams(layoutParams4);
                appCompatTextView.setGravity(1);
                ogf ogf = puf.m;
                ogf.b(appCompatTextView, uy4.b);
                b0h.H(appCompatTextView, new xg5(3, (Continuation) null, 5));
                appCompatTextView.setEllipsize(TextUtils.TruncateAt.END);
                appCompatTextView.setMaxLines(1);
                linearLayout5.addView(appCompatTextView);
                AppCompatTextView appCompatTextView2 = new AppCompatTextView(linearLayout5.getContext(), (AttributeSet) null);
                appCompatTextView2.setId(jxa.E);
                LinearLayout.LayoutParams layoutParams5 = new LinearLayout.LayoutParams(-2, -2);
                float f11 = (float) 4;
                layoutParams5.setMarginStart(MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f11));
                layoutParams5.setMarginEnd(MathKt.roundToInt(f11 * vo4.c().getDisplayMetrics().density));
                appCompatTextView2.setLayoutParams(layoutParams5);
                appCompatTextView2.setText("·");
                appCompatTextView2.setGravity(1);
                ogf.b(appCompatTextView2, uy4.b);
                b0h.H(appCompatTextView2, new xg5(3, (Continuation) null, 4));
                linearLayout5.addView(appCompatTextView2);
                TextView textView2 = new TextView(linearLayout5.getContext());
                textView2.setId(jxa.h1);
                LinearLayout.LayoutParams layoutParams6 = new LinearLayout.LayoutParams(-2, -2);
                layoutParams6.rightMargin = MathKt.roundToInt(f10 * vo4.c().getDisplayMetrics().density);
                textView2.setLayoutParams(layoutParams6);
                textView2.setGravity(1);
                puf.o.b(textView2, uy4.b);
                textView2.setTextColor(js9.e(textView2.getContext()).f().getText().f);
                linearLayout5.addView(textView2);
                return Unit.INSTANCE;
            default:
                CoordinatorLayout coordinatorLayout = (CoordinatorLayout) obj;
                KProperty[] kPropertyArr7 = ProfileScreen.D0;
                m5c m5c5 = new m5c(profileScreen, 0);
                profileScreen.getClass();
                AppBarLayout appBarLayout2 = new AppBarLayout(coordinatorLayout.getContext(), (AttributeSet) null);
                appBarLayout2.setId(jxa.d1);
                appBarLayout2.setLayoutParams(new ViewGroup.LayoutParams(-1, -2));
                appBarLayout2.setBackground((Drawable) null);
                m5c5.invoke(appBarLayout2);
                coordinatorLayout.addView(appBarLayout2);
                NestedScrollView nestedScrollView = new NestedScrollView(coordinatorLayout.getContext(), (AttributeSet) null);
                wz3 wz3 = new wz3(-1, -1);
                wz3.b(new AppBarLayout.ScrollingViewBehavior());
                nestedScrollView.setLayoutParams(wz3);
                m5c m5c6 = new m5c(profileScreen, 2);
                LinearLayout linearLayout6 = new LinearLayout(nestedScrollView.getContext());
                linearLayout6.setLayoutParams(new LinearLayout.LayoutParams(-1, -2));
                linearLayout6.setOrientation(1);
                m5c6.invoke(linearLayout6);
                nestedScrollView.addView(linearLayout6);
                Unit unit2 = Unit.INSTANCE;
                coordinatorLayout.addView(nestedScrollView);
                return Unit.INSTANCE;
        }
    }
}
