package defpackage;

import android.graphics.drawable.Drawable;
import android.graphics.drawable.GradientDrawable;
import android.graphics.drawable.InsetDrawable;
import android.view.View;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.Space;
import android.widget.TextView;
import kotlin.Unit;
import kotlin.coroutines.Continuation;
import kotlin.jvm.functions.Function1;
import kotlin.math.MathKt;
import kotlin.reflect.KProperty;
import one.me.sdk.messagewrite.recordcontrols.RecordControlsWidget;

/* renamed from: rwc  reason: default package */
public final /* synthetic */ class rwc implements Function1 {
    public final /* synthetic */ int a;
    public final /* synthetic */ RecordControlsWidget b;

    public /* synthetic */ rwc(RecordControlsWidget recordControlsWidget, int i) {
        this.a = i;
        this.b = recordControlsWidget;
    }

    public final Object invoke(Object obj) {
        RecordControlsWidget recordControlsWidget = this.b;
        switch (this.a) {
            case 0:
                LinearLayout linearLayout = (LinearLayout) obj;
                KProperty[] kPropertyArr = RecordControlsWidget.g1;
                recordControlsWidget.getClass();
                View view = new View(linearLayout.getContext());
                view.setId(xya.h);
                float f = (float) 8;
                LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f), MathKt.roundToInt(f * vo4.c().getDisplayMetrics().density));
                layoutParams.setMargins(MathKt.roundToInt(((float) 20) * vo4.c().getDisplayMetrics().density), 0, MathKt.roundToInt(((float) 10) * vo4.c().getDisplayMetrics().density), 0);
                layoutParams.gravity = 16;
                view.setLayoutParams(layoutParams);
                view.setBackground((GradientDrawable) recordControlsWidget.Q0.getValue());
                b0h.H(view, new vwc(recordControlsWidget, (Continuation) null, 0));
                linearLayout.addView(view);
                ImageView imageView = new ImageView(linearLayout.getContext());
                imageView.setId(xya.r);
                float f2 = (float) 36;
                LinearLayout.LayoutParams layoutParams2 = new LinearLayout.LayoutParams(MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f2), MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f2));
                layoutParams2.gravity = 16;
                layoutParams2.leftMargin = MathKt.roundToInt(((float) 6) * vo4.c().getDisplayMetrics().density);
                imageView.setLayoutParams(layoutParams2);
                float f3 = (float) 4;
                int roundToInt = MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f3);
                imageView.setPadding(roundToInt, roundToInt, roundToInt, roundToInt);
                imageView.setImageResource(cad.z);
                imageView.setVisibility(8);
                linearLayout.addView(imageView);
                TextView textView = new TextView(linearLayout.getContext());
                textView.setId(xya.i);
                LinearLayout.LayoutParams layoutParams3 = new LinearLayout.LayoutParams(-2, -2);
                layoutParams3.gravity = 16;
                layoutParams3.setMarginStart(MathKt.roundToInt(f3 * vo4.c().getDisplayMetrics().density));
                textView.setLayoutParams(layoutParams3);
                puf.k.b(textView, uy4.b);
                b0h.H(textView, new ra(3, (Continuation) null, 21));
                linearLayout.addView(textView);
                rwc rwc = new rwc(recordControlsWidget, 5);
                FrameLayout frameLayout = new FrameLayout(linearLayout.getContext());
                LinearLayout.LayoutParams layoutParams4 = new LinearLayout.LayoutParams(MathKt.roundToInt(((float) 0) * vo4.c().getDisplayMetrics().density), -1);
                layoutParams4.weight = 1.0f;
                frameLayout.setLayoutParams(layoutParams4);
                rwc.invoke(frameLayout);
                linearLayout.addView(frameLayout);
                Space space = new Space(linearLayout.getContext());
                space.setLayoutParams(new LinearLayout.LayoutParams((int) (((float) MathKt.roundToInt(f2 * vo4.c().getDisplayMetrics().density)) * 1.45f), -2));
                linearLayout.addView(space);
                return Unit.INSTANCE;
            case 1:
                FrameLayout frameLayout2 = (FrameLayout) obj;
                KProperty[] kPropertyArr2 = RecordControlsWidget.g1;
                rwc rwc2 = new rwc(recordControlsWidget, 3);
                recordControlsWidget.getClass();
                LinearLayout linearLayout2 = new LinearLayout(frameLayout2.getContext());
                linearLayout2.setId(xya.s);
                float f4 = (float) 36;
                FrameLayout.LayoutParams layoutParams5 = new FrameLayout.LayoutParams(-1, MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f4));
                float f5 = (float) 6;
                layoutParams5.setMargins(MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f5), MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f5), MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f5), MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f5));
                layoutParams5.gravity = 49;
                linearLayout2.setLayoutParams(layoutParams5);
                linearLayout2.setMinimumHeight(MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f4));
                float f6 = (float) 4;
                int roundToInt2 = MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f6);
                linearLayout2.setPadding(roundToInt2, roundToInt2, roundToInt2, roundToInt2);
                linearLayout2.setBackground(recordControlsWidget.E0());
                b0h.H(linearLayout2, new mh0((Object) recordControlsWidget, (Continuation) null, 13));
                rwc2.invoke(linearLayout2);
                frameLayout2.addView(linearLayout2);
                ImageView imageView2 = new ImageView(frameLayout2.getContext());
                imageView2.setId(xya.q);
                FrameLayout.LayoutParams layoutParams6 = new FrameLayout.LayoutParams(MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f4), MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f4));
                layoutParams6.gravity = 8388691;
                layoutParams6.setMargins(MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f5), 0, MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f5), MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f5));
                imageView2.setLayoutParams(layoutParams6);
                int roundToInt3 = MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f6);
                imageView2.setPadding(roundToInt3, roundToInt3, roundToInt3, roundToInt3);
                imageView2.setImageResource(cad.z);
                b0h.H(imageView2, new xd2(3, (Continuation) null, 8));
                ct.G(imageView2, 300, new twc(recordControlsWidget, 1));
                frameLayout2.addView(imageView2);
                ImageView imageView3 = new ImageView(frameLayout2.getContext());
                imageView3.setId(xya.m);
                FrameLayout.LayoutParams layoutParams7 = new FrameLayout.LayoutParams(MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f4), MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f4));
                layoutParams7.gravity = 81;
                layoutParams7.setMargins(layoutParams7.leftMargin, layoutParams7.topMargin, layoutParams7.rightMargin, MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f5));
                imageView3.setLayoutParams(layoutParams7);
                int roundToInt4 = MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f6);
                imageView3.setPadding(roundToInt4, roundToInt4, roundToInt4, roundToInt4);
                imageView3.setImageResource(cad.L0);
                b0h.H(imageView3, new xd2(3, (Continuation) null, 6));
                ct.G(imageView3, 300, new twc(recordControlsWidget, 2));
                frameLayout2.addView(imageView3);
                ImageView imageView4 = new ImageView(frameLayout2.getContext());
                imageView4.setId(xya.o);
                FrameLayout.LayoutParams layoutParams8 = new FrameLayout.LayoutParams(MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f4), MathKt.roundToInt(f4 * vo4.c().getDisplayMetrics().density));
                layoutParams8.gravity = 81;
                float f7 = (float) 0;
                layoutParams8.setMargins(MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f7), MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f7), MathKt.roundToInt(f7 * vo4.c().getDisplayMetrics().density), MathKt.roundToInt(f5 * vo4.c().getDisplayMetrics().density));
                imageView4.setLayoutParams(layoutParams8);
                int roundToInt5 = MathKt.roundToInt(f6 * vo4.c().getDisplayMetrics().density);
                imageView4.setPadding(roundToInt5, roundToInt5, roundToInt5, roundToInt5);
                imageView4.setImageResource(cad.a1);
                b0h.H(imageView4, new xd2(3, (Continuation) null, 7));
                imageView4.setVisibility(8);
                ct.G(imageView4, 300, new twc(recordControlsWidget, 0));
                frameLayout2.addView(imageView4);
                return Unit.INSTANCE;
            case 2:
                FrameLayout frameLayout3 = (FrameLayout) obj;
                KProperty[] kPropertyArr3 = RecordControlsWidget.g1;
                rwc rwc3 = new rwc(recordControlsWidget, 4);
                recordControlsWidget.getClass();
                FrameLayout frameLayout4 = new FrameLayout(frameLayout3.getContext());
                frameLayout4.setId(xya.c);
                FrameLayout.LayoutParams layoutParams9 = new FrameLayout.LayoutParams(-1, -1);
                layoutParams9.gravity = 17;
                frameLayout4.setLayoutParams(layoutParams9);
                rwc3.invoke(frameLayout4);
                frameLayout3.addView(frameLayout4);
                ImageView imageView5 = new ImageView(frameLayout3.getContext());
                imageView5.setId(xya.a);
                float f8 = (float) 36;
                FrameLayout.LayoutParams layoutParams10 = new FrameLayout.LayoutParams(MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f8), MathKt.roundToInt(f8 * vo4.c().getDisplayMetrics().density));
                layoutParams10.gravity = 17;
                imageView5.setLayoutParams(layoutParams10);
                int roundToInt6 = MathKt.roundToInt(((float) 4) * vo4.c().getDisplayMetrics().density);
                imageView5.setPadding(roundToInt6, roundToInt6, roundToInt6, roundToInt6);
                imageView5.setScaleType(ImageView.ScaleType.CENTER_INSIDE);
                imageView5.setImageDrawable(recordControlsWidget.v0());
                ct.G(imageView5, 300, new twc(recordControlsWidget, 3));
                b0h.H(imageView5, new qrb((Object) recordControlsWidget, (Continuation) null, 5));
                frameLayout3.addView(imageView5);
                return Unit.INSTANCE;
            case 3:
                LinearLayout linearLayout3 = (LinearLayout) obj;
                KProperty[] kPropertyArr4 = RecordControlsWidget.g1;
                rwc rwc4 = new rwc(recordControlsWidget, 6);
                recordControlsWidget.getClass();
                FrameLayout frameLayout5 = new FrameLayout(linearLayout3.getContext());
                float f9 = (float) 28;
                frameLayout5.setLayoutParams(new LinearLayout.LayoutParams(MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f9), MathKt.roundToInt(f9 * vo4.c().getDisplayMetrics().density)));
                rwc4.invoke(frameLayout5);
                linearLayout3.addView(frameLayout5);
                TextView textView2 = new TextView(linearLayout3.getContext());
                textView2.setId(xya.k);
                LinearLayout.LayoutParams layoutParams11 = new LinearLayout.LayoutParams(-2, -2);
                layoutParams11.gravity = 16;
                layoutParams11.setMarginStart(MathKt.roundToInt(((float) 4) * vo4.c().getDisplayMetrics().density));
                textView2.setLayoutParams(layoutParams11);
                puf.k.b(textView2, uy4.b);
                b0h.H(textView2, new x2(recordControlsWidget, (Continuation) null, 27));
                linearLayout3.addView(textView2);
                c80 c80 = new c80(linearLayout3.getContext());
                c80.setId(xya.t);
                LinearLayout.LayoutParams layoutParams12 = new LinearLayout.LayoutParams(MathKt.roundToInt(((float) 0) * vo4.c().getDisplayMetrics().density), MathKt.roundToInt(((float) 24) * vo4.c().getDisplayMetrics().density));
                layoutParams12.setMarginStart(MathKt.roundToInt(((float) 8) * vo4.c().getDisplayMetrics().density));
                layoutParams12.setMarginEnd(MathKt.roundToInt(((float) 2) * vo4.c().getDisplayMetrics().density));
                layoutParams12.weight = 1.0f;
                layoutParams12.gravity = 16;
                c80.setLayoutParams(layoutParams12);
                c80.setListener(new xe8(22, c80, recordControlsWidget));
                linearLayout3.addView(c80);
                return Unit.INSTANCE;
            case 4:
                FrameLayout frameLayout6 = (FrameLayout) obj;
                KProperty[] kPropertyArr5 = RecordControlsWidget.g1;
                recordControlsWidget.getClass();
                FrameLayout frameLayout7 = new FrameLayout(frameLayout6.getContext());
                frameLayout7.setId(xya.b);
                float f10 = (float) 84;
                FrameLayout.LayoutParams layoutParams13 = new FrameLayout.LayoutParams(MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f10), MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f10));
                layoutParams13.gravity = 17;
                frameLayout7.setLayoutParams(layoutParams13);
                frameLayout7.setBackground((GradientDrawable) recordControlsWidget.N0.getValue());
                b0h.H(frameLayout7, new uwc(recordControlsWidget, (Continuation) null, 1));
                frameLayout6.addView(frameLayout7);
                FrameLayout frameLayout8 = new FrameLayout(frameLayout6.getContext());
                FrameLayout.LayoutParams layoutParams14 = new FrameLayout.LayoutParams(MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f10), MathKt.roundToInt(f10 * vo4.c().getDisplayMetrics().density));
                layoutParams14.gravity = 17;
                frameLayout8.setLayoutParams(layoutParams14);
                frameLayout8.setBackground((GradientDrawable) recordControlsWidget.O0.getValue());
                b0h.H(frameLayout8, new uwc(recordControlsWidget, (Continuation) null, 0));
                frameLayout6.addView(frameLayout8);
                return Unit.INSTANCE;
            case 5:
                FrameLayout frameLayout9 = (FrameLayout) obj;
                KProperty[] kPropertyArr6 = RecordControlsWidget.g1;
                recordControlsWidget.getClass();
                TextView textView3 = new TextView(frameLayout9.getContext());
                textView3.setId(xya.g);
                FrameLayout.LayoutParams layoutParams15 = new FrameLayout.LayoutParams(-2, -1);
                layoutParams15.gravity = 17;
                textView3.setLayoutParams(layoutParams15);
                textView3.setGravity(17);
                textView3.setText(yya.h);
                textView3.setCompoundDrawablesRelativeWithIntrinsicBounds((InsetDrawable) recordControlsWidget.M0.getValue(), (Drawable) null, (Drawable) null, (Drawable) null);
                puf.o.b(textView3, uy4.b);
                b0h.H(textView3, new qrb((Object) recordControlsWidget, (Continuation) null, 6));
                frameLayout9.addView(textView3);
                return Unit.INSTANCE;
            default:
                FrameLayout frameLayout10 = (FrameLayout) obj;
                KProperty[] kPropertyArr7 = RecordControlsWidget.g1;
                recordControlsWidget.getClass();
                View view2 = new View(frameLayout10.getContext());
                view2.setId(xya.j);
                float f11 = (float) 8;
                FrameLayout.LayoutParams layoutParams16 = new FrameLayout.LayoutParams(MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f11), MathKt.roundToInt(f11 * vo4.c().getDisplayMetrics().density));
                layoutParams16.gravity = 17;
                view2.setLayoutParams(layoutParams16);
                view2.setBackground((GradientDrawable) recordControlsWidget.Q0.getValue());
                b0h.H(view2, new vwc(recordControlsWidget, (Continuation) null, 1));
                frameLayout10.addView(view2);
                ImageView imageView6 = new ImageView(frameLayout10.getContext());
                imageView6.setId(xya.n);
                float f12 = (float) 28;
                imageView6.setLayoutParams(new LinearLayout.LayoutParams(MathKt.roundToInt(vo4.c().getDisplayMetrics().density * f12), MathKt.roundToInt(f12 * vo4.c().getDisplayMetrics().density)));
                imageView6.setImageDrawable((Drawable) recordControlsWidget.I0.getValue());
                imageView6.setVisibility(8);
                b0h.H(imageView6, new vwc(recordControlsWidget, (Continuation) null, 2));
                ct.G(imageView6, 300, new twc(recordControlsWidget, 4));
                frameLayout10.addView(imageView6);
                return Unit.INSTANCE;
        }
    }
}
